"""Producer LLM pass: per-segment script generation via async iterator (Phase 3 / decision 2a).

Two-step pipeline (prompt_design.md §4):
  Step 1 (deterministic): select_segments() in producer/segments.py
  Step 2 (this module):   LLM writes per-segment scripts via stream_episode_script()
"""

from __future__ import annotations

import asyncio
import json
import os
from typing import AsyncIterator, TypedDict

import anthropic

from agents.protocol import Brief, Pitch
from producer import DEFAULT_LLM_MODEL
from producer.events import emit
from producer.segments import TARGET_EPISODE_SECS

# ── Output types ─────────────────────────────────────────────────────


class SegmentScript(TypedDict):
    agent: str
    pitch_title: str
    segue_in: str  # empty for first segment
    script: str
    estimated_length_sec: int


class EpisodeScript(TypedDict):
    cold_open: str
    segments: list[SegmentScript]
    sign_off: str


# ── Constants ────────────────────────────────────────────────────────

MODEL = os.environ.get("PRODUCER_LLM_MODEL", DEFAULT_LLM_MODEL)
SEGMENT_MAX_TOKENS = 2048
_MIN_SCRIPT_CHARS = 20

# ── System prompt ────────────────────────────────────────────────────

SYSTEM_PROMPT = """\
You are a radio show producer. You receive a single selected segment \
(with a creative hook from a domain agent) and today's context. \
Your job is to write the script for this one segment, including a segue in.

## Hard rules

1. **Cannot drop segments.** The single input segment must appear in \
   the output. pitch_title must round-trip verbatim.
2. **Cannot invent segments.** No topic or content beyond what is provided.
3. **Produce exactly one segment script** with:
   - `segue_in` (5–10s) when `is_first=false`; empty string when `is_first=true`
   - `script` — the spoken script for this segment; warm, conversational tone
   - The cold open and sign-off are generated by separate calls; do not produce them here.
4. **First segment's `segue_in` is empty.** Pass-through: when `is_first=true`, \
   set segue_in to an empty string.
5. **Today's context** should be woven into the script where \
   natural. Do not force-fit weather into every segment.
6. **Segment ordering heuristics** (guidance, not hard rules):
   - Time-sensitive content first (calendar, weather)
   - Taste content after (youtube, alices)
   - Within taste: rising/discovery claim_kinds are more narratively \
     interesting as mid-show energy; durable works as a comfortable closer
7. **Respect claim_kind and provenance_shape per segment.** Do not add \
   temporal claims the agent's hook didn't make. If claim_kind is \
   "neutral", the segment script should be factual, not enthusiastic.

## Field legend

The `segment` input carries these fields:

- `agent` — source agent name; informs ordering heuristics.
- `title` — short label; must round-trip verbatim in `pitch_title`.
- `hook` — creative brief from the agent. Not spoken verbatim. For taste \
  agents, caps the phrasing you may use (see Hook vs. data layering). For \
  context agents, a one-line summary of the data.
- `rationale` — why the agent selected this topic. Context for tone; never spoken.
- `source_refs` — channel names / video titles (human-readable, NOT IDs). \
  Reference sparingly where natural ("a channel you've been subscribed to"). \
  Do not recite the full list.
- `data` — structured payload from the agent. Per-agent crib below.
- `priority` — already consumed upstream (agent self-report weighted by \
  Producer memory, used during Step-1 selection). Do not re-rank on it.
- `suggested_length_sec` — scheduling metadata, not a script-level knob.
- `claim_kind` — temporal framing permission. See claim_kind directives below.
- `provenance_shape` — evidence framing permission. Already enforced by the \
  agent in the hook; informational here.
- `thin_signal` — when `true`, the agent had insufficient personalization data.

## claim_kind directives

Each segment's `claim_kind` governs temporal framing. Do not exceed the \
permitted phrasing for the segment's claim_kind:

- **durable**: Permitted: "you've been into X", "a longtime favorite", \
  reference subscription dates. Prohibited: "lately", "recently", "getting into".
- **rising**: Permitted: "you've been getting into X lately", \
  "X is taking over your feed". Prohibited: "longtime", "always been".
- **discovery**: Permitted: "you've been exploring X", \
  "some X caught your eye recently". Prohibited: "deep into", "longtime", "always".
- **neutral**: Permitted: factual — "X showed up in your subs/likes", \
  reference specific channel/video names from `source_refs`. Prohibited: \
  any temporal or intensity claim.

## Per-agent data crib

What you'll find in `data` per agent:

- **weather** — `data.current` (temp/condition/wind), `data.day_ahead` \
  (upcoming high/low/sunset), `data.notable_facts` (top 3 ranked \
  radio-interesting facts), `data.air_quality`, `data.location_name`. \
  Ignore `hourly_forecast` and `day_past` unless surfacing a specific hour matters.
- **calendar** — `data.api_reachable` (bool), `data.events[]` with \
  `summary`, `start`, `end`, `duration_min`, `attendee_count`, `is_recurring`, \
  `has_video_call`, `organizer`.
- **youtube** / **alices** — `data` is usually `{}`. The hook + rationale \
  + source_refs are the substrate.

## Hook vs. data layering

For taste agents (`youtube`, `alices`): the hook is the phrasing ceiling. \
`claim_kind` and `provenance_shape` bound what you may claim; `data` is \
read-only context for tone calibration only. Do not combine facts from \
`data` into new temporal or intensity claims the hook did not make.

For context agents (`weather`, `calendar`): `data` is the content source. \
`hook` is a one-line safety net / summary. Prefer `data` when writing the \
segment body; use `hook` only as a fallback framing.

`provenance_shape` is already enforced by the agent when writing the hook. \
You do not need a shape table. Do not invent references to subscriptions, \
channels, or likes beyond what the hook already cites.

## thin_signal handling

When `thin_signal: true`, write a general-interest segment in the agent's \
domain — no personalization, no channels/subs/events by name. Optionally \
close with one factual sentence:

- **youtube** / **alices** — "This will get more personal as your YouTube activity grows." \
  (cause: sparse subs/likes — not actionable in the short term)
- **weather** — "Local forecast wasn't available today." (cause: location \
  skipped at generation, or forecast API failure — both opaque from the script's POV)

Keep the line factual and brief. If awkward, omit it. Never recite reasons \
across multiple segments — one per thin_signal segment, in that segment's \
own script.

## Voice

Warm, conversational, like a knowledgeable friend who curates your \
listening. Not a DJ — no hype, no catchphrases. Natural pacing.

## Output format

Return a JSON object for this single segment with exactly these keys:
{
  "agent": "agent_name (same as input)",
  "pitch_title": "from input — must round-trip verbatim",
  "segue_in": "transition from previous segment (empty string when is_first=true)",
  "script": "the spoken script for this segment",
  "estimated_length_sec": 60
}

Return ONLY the JSON object — no markdown fences, no commentary.
"""


# ── LLM call ─────────────────────────────────────────────────────────

_client = anthropic.Anthropic()


async def generate_segment(
    segment: Pitch,
    brief: Brief,
    is_first: bool,
) -> SegmentScript:
    """Single async LLM call producing one SegmentScript.

    Enforces first-segue-empty and script-length-floor internally.
    No events emitted here — stream_episode_script handles SSE.
    """
    payload = {
        "segment": {
            "agent": segment["agent"],
            "title": segment["title"],
            "hook": segment["hook"],
            "rationale": segment.get("rationale", ""),
            "source_refs": segment.get("source_refs", []),
            "data": segment.get("data", {}),
            "priority": segment["priority"],
            "claim_kind": segment.get("claim_kind", "neutral"),
            "provenance_shape": segment.get("provenance_shape", "balanced"),
            "thin_signal": segment.get("thin_signal", False),
            "suggested_length_sec": segment["suggested_length_sec"],
        },
        "today_context": dict(brief["today_context"]),
        "is_first": is_first,
        "target_total_secs": TARGET_EPISODE_SECS,
    }
    user_msg = json.dumps(payload, indent=2)

    response = await asyncio.to_thread(
        _client.messages.create,
        model=MODEL,
        max_tokens=SEGMENT_MAX_TOKENS,
        system=SYSTEM_PROMPT,
        messages=[{"role": "user", "content": user_msg}],
        timeout=30.0,
    )

    if not response.content or response.content[0].type != "text":
        raise ValueError("LLM returned no text content")
    raw = response.content[0].text.strip()
    if raw.startswith("```"):
        raw = raw.split("\n", 1)[1] if "\n" in raw else raw[3:]
        if raw.endswith("```"):
            raw = raw[:-3].strip()

    data = json.loads(raw)

    seg = SegmentScript(
        agent=data["agent"],
        pitch_title=data["pitch_title"],
        segue_in=data.get("segue_in", ""),
        script=data["script"],
        estimated_length_sec=data.get("estimated_length_sec", 60),
    )

    if is_first and seg["segue_in"].strip():
        raise ValueError(
            f"First segment must have empty segue_in. Got: {seg['segue_in']!r}"
        )

    if len(seg["script"].strip()) < _MIN_SCRIPT_CHARS:
        raise ValueError(
            f"Segment ({seg['agent']}/{seg['pitch_title']}) script too short: "
            f"{len(seg['script'])} chars (min {_MIN_SCRIPT_CHARS})"
        )

    return seg


async def stream_episode_script(
    selected: list[Pitch],
    brief: Brief,
) -> AsyncIterator[SegmentScript]:
    """Async generator yielding one SegmentScript per input pitch.

    Emits script.segment.done SSE per segment.
    Enforces cannot-drop-segments at end.
    Re-enforces script-length floor on each segment (defense in depth).
    """
    input_keys = {(p["agent"], p["title"]) for p in selected}
    output_keys: set[tuple[str, str]] = set()

    for i, pitch in enumerate(selected):
        seg = await generate_segment(pitch, brief, is_first=(i == 0))

        if i == 0 and seg["segue_in"].strip():
            raise ValueError(
                f"First segment must have empty segue_in. Got: {seg['segue_in']!r}"
            )

        if len(seg["script"].strip()) < _MIN_SCRIPT_CHARS:
            raise ValueError(
                f"Segment ({seg['agent']}/{seg['pitch_title']}) script too short: "
                f"{len(seg['script'])} chars (min {_MIN_SCRIPT_CHARS})"
            )

        emit("script.segment.done", {
            "index": i,
            "agent": seg["agent"],
            "pitch_title": seg["pitch_title"],
        })

        output_keys.add((seg["agent"], seg["pitch_title"]))
        yield seg

    missing = input_keys - output_keys
    if missing:
        agents = [a for a, _ in missing]
        raise ValueError(f"LLM dropped {len(missing)} segment(s) from agents: {agents}")


def generate_episode_script(
    selected: list[Pitch],
    brief: Brief,
) -> EpisodeScript:
    """Sync back-compat collector. Runs stream_episode_script and collects results.

    Task 3.2 replaces the cold_open and sign_off placeholders.
    """
    async def _collect() -> list[SegmentScript]:
        return [seg async for seg in stream_episode_script(selected, brief)]

    segments = asyncio.run(_collect())

    return EpisodeScript(
        cold_open="(cold open generated by coordinator in Phase 3.2)",
        segments=segments,
        sign_off="(sign-off generated by coordinator in Phase 3.2)",
    )
